android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/events/EventEmitter.kt
Removes putIfAbsent that is an API 24+ method. Replaced with kotlin method
=> [EXP-17541] Remove putIfAbsent usage

android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/AttributeOperation.kt, android/airship-framework-proxy/src/test/java/com/urbanairship/android/framework/proxy/AttributeOperationTest.kt, ios/AirshipFrameworkProxy.xcodeproj/project.pbxproj, ios/AirshipFrameworkProxy/AttributeOperation.swift, ios/AirshipFrameworkProxyTests/AttributeOperationTest.swift
Fixes parsing on Android and added missing tests to both iOS and Android to ensure same parsing.
=> Fix attribute operation parsing

android/airship-framework-proxy/src/test/java/com/urbanairship/android/framework/proxy/AttributeOperationTest.kt, android/airship-framework-proxy/src/test/java/com/urbanairship/android/framework/proxy/ScopedSubscriptionListOperationTest.kt, ios/AirshipFrameworkProxy.xcodeproj/project.pbxproj, ios/AirshipFrameworkProxy/AttributeOperation.swift, ios/AirshipFrameworkProxy/Proxies/AirshipChannelProxy.swift, ios/AirshipFrameworkProxy/Proxies/AirshipContactProxy.swift, ios/AirshipFrameworkProxy/ScopedSubscriptionListOperation.swift, ios/AirshipFrameworkProxyTests/AttributeOperationTest.swift, ios/AirshipFrameworkProxyTests/ScopedSubscriptionListOperationTest.swift
Fix applying attributes on iOS. Working on adding Android tests now.
=> [GH-10] Fix iOS attribute issue

AirshipFrameworkProxy.podspec, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/TagOperation.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/ChannelProxy.kt, android/airship-framework-proxy/src/test/java/com/urbanairship/android/framework/proxy/TagOperationTest.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy.xcodeproj/project.pbxproj, ios/AirshipFrameworkProxy/Proxies/AirshipChannelProxy.swift, ios/AirshipFrameworkProxy/TagOperation.swift, ios/AirshipFrameworkProxyTests/TagOperationTest.swift, ios/Podfile, ios/Podfile.lock
=> [MOBILE-3864] Add editTags to proxy

AirshipFrameworkProxy.podspec, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/FeatureFlagManagerProxy.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/MessageCenterProxy.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/AirshipProxyEventEmitter.swift, ios/AirshipFrameworkProxy/Proxies/AirshipFeatureFlagManagerProxy.swift, ios/AirshipFrameworkProxy/Proxies/AirshipMessageCenterProxy.swift, ios/Podfile, ios/Podfile.lock
Breaking change with feature flags to make the interaction event work.
=> Release 5.0.0

AirshipFrameworkProxy.podspec, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/FeatureFlagManagerProxy.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/Proxies/AirshipMessageCenterProxy.swift
Changes:
- Fixes iOS MC iconListURL to iconListUrl
- Fixes flag proxy parsing
=> Release 5.0.1

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml
=> Update proxy to 5.1.1 iOS to 17.7.3 and Android to 17.7.2

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 5.1.2

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/DefaultMessageCenterUI.swift, ios/AirshipFrameworkProxy/ProxyConfig.swift
iOS the message center did not have a nav bar and i need to expose a constructor
=> Minor fixes for cordova

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> update iOS SDK

AirshipFrameworkProxy.podspec, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/BaseAutopilot.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/ProxyConfig.swift, ios/Podfile
Need to expose apply methods for capacitor
=> Release 5.4.1

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml, ios/Podfile
=> Release 6.1.2

ios/AirshipFrameworkProxy/ProxyConfig.swift
Following this PR :  https://github.com/urbanairship/react-native-airship/pull/578
=> [MOBILE-4628] Add isWebViewInspectionEnabled config field

AirshipFrameworkProxy.podspec, Package.swift, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/BaseAutopilot.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/NotificationStatus.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/PushProxy.kt, android/airship-framework-proxy/src/test/java/com/urbanairship/android/framework/proxy/NotificationStatusTest.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/NotificationStatus.swift, ios/AirshipFrameworkProxy/Proxies/AirshipPushProxy.swift, ios/Podfile, ios/Podfile.lock
Adds fallback support to enableNotifications and `notificationPermissionStatus` to the NotificationStatus object. Breaking change since Android is now suspending.
=> Release 8.0.0

AirshipFrameworkProxy.podspec, Package.swift, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/MessageCenterProxy.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/Proxies/AirshipMessageCenterProxy.swift, ios/Podfile
Adds a new method to show the message center regardless of auto launch MC being enabled or not.
=> Release 8.1.0

AirshipFrameworkProxy.podspec, android/airship-framework-proxy/build.gradle, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/LiveUpdatesManagerProxy.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/LiveActivity/LiveActivityManager.swift, ios/AirshipFrameworkProxy/LiveActivity/LiveActivityRequest.swift
Adds LiveUpdateManagerProxy and updated iOS apis to match
=> Live updates

ios/AirshipFrameworkProxy/DefaultMessageCenterUI.swift
We have two back buttons on the standalone message view
=> Fix double back button

AirshipFrameworkProxy.podspec, android/gradle/libs.versions.toml
=> Release 10.1.1 

ios/AirshipFrameworkProxy.xcodeproj/project.pbxproj, ios/AirshipFrameworkProxy/AirshipDelegate.swift, ios/AirshipFrameworkProxy/AirshipPluginForwardListeners.swift, ios/AirshipFrameworkProxy/AirshipProxyEvent.swift, ios/AirshipFrameworkProxy/Loader/AirshipFrameworkProxyLoader.swift, ios/AirshipFrameworkProxy/Loader/AirshipPluginExtenderProtocol.swift, ios/AirshipFrameworkProxy/Loader/AirshipPluginLoaderProtocol.swift, ios/AirshipFrameworkProxy/Proxies/AirshipProxy.swift, ios/AirshipFrameworkProxy/Proxies/AirshipPushProxy.swift
Adds ability to modify config programmatically and set forward listeners.
=> iOS Add hybrid app hooks

AirshipFrameworkProxy.podspec, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 11.0.2

AirshipFrameworkProxy.podspec, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 11.0.3

.gitignore, AirshipFrameworkProxy.podspec, Package.resolved, android/gradle/libs.versions.toml
=> Release 11.0.4

AirshipFrameworkProxy.podspec, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
Release 11.0.6
- Proxy 11.0.5 -> 11.0.6
- Android 18.4.1 -> 18.4.2
- iOS 18.12.1 -> 18.12.2
=> Release 11.0.6

AirshipFrameworkProxy.podspec, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 11.1.0

AirshipFrameworkProxy.podspec, Package.swift, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/proxies/FeatureFlagManagerProxy.kt, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/Proxies/AirshipFeatureFlagManagerProxy.swift, ios/Podfile, ios/Podfile.lock
Adds ff resultCache proxy methods and updates to latest SDK
=> Release 11.2.0

AirshipFrameworkProxy.podspec, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 11.2.2

AirshipFrameworkProxy.podspec, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/AirshipDelegate.swift, ios/AirshipFrameworkProxy/AirshipExtensions.swift, ios/AirshipFrameworkProxy/AirshipProxyEvent.swift, ios/AirshipFrameworkProxy/LiveActivity/LiveActivityContent.swift, ios/AirshipFrameworkProxy/LiveActivity/LiveActivityRequest.swift, ios/AirshipFrameworkProxy/ProxyPushPayload.swift, ios/AirshipFrameworkProxy/PushUtils.swift, ios/Podfile, ios/Podfile.lock
Pod is pointing to 19.0.1 until its deployed
=> Update iOS SDK to 19.0.2

AirshipFrameworkProxy.podspec, Package.resolved, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/AirshipDelegate.swift, ios/AirshipFrameworkProxy/Proxies/AirshipProxy.swift
=> Release 12.1.2

AirshipFrameworkProxy.podspec, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
=> Release 12.1.3

AirshipFrameworkProxy.podspec, Gemfile, Gemfile.lock, Package.resolved, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, ios/Podfile.lock
Also bumped the REXML version in our Gemfile due to dependabot warnings.
=> Bump to Android 19.2.0 / iOS 19.1.0

AirshipFrameworkProxy.podspec, Package.swift, android/gradle/libs.versions.toml, ios/Podfile, scripts/version_bump.sh
Release 14.1.1 and added update version script
=> Release 14.1.1

AirshipFrameworkProxy.podspec, Package.swift, android/gradle/libs.versions.toml
=> Release 14.5.0

AirshipFrameworkProxy.podspec, Package.swift, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/BaseAutopilot.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/ProxyConfig.kt, android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/Utils.kt, android/gradle/libs.versions.toml
=> Release 14.5.1

AirshipFrameworkProxy.podspec, Package.swift, android/gradle/libs.versions.toml, ios/AirshipFrameworkProxy/Proxies/AirshipProxy.swift
=> Release 14.6.0
